# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: kennyã®åšå®¢ # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  kennyã®åšå®¢ # ç½‘ç«™çš„æ ‡é¢˜
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.png # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: Home # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About Us
      href: /about-us
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: Tech blogs
          href: /blog/category/tech
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: Life blogs
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # å­èœå•é¡¹é…ç½®
    - id: contact
      text: Contact
      href: "mailto:patiences6092@gmail.com"
      target: _blank # åœ¨æ–°æ ‡ç­¾é¡µæ‰“å¼€
      svg: "material-symbols:attach-email-outline-rounded"
      

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: kenny # ç”¨æˆ·å
  site: "https://viken.top/" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://viken.top/" # é“¾æ¥
        ariaLabel: è¿”å›æˆ‘çš„ä¸»é¡µ # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: è¿”å›æˆ‘çš„ä¸»é¡µ # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:home-2-line"
      
      - href: "https://pan.viken.top/"
        ariaLabel: "å‰å¾€æˆ‘çš„ç½‘ç›˜"
        title: "å‰å¾€æˆ‘çš„ç½‘ç›˜"
        svg: "ri:cloud-line"  # äº‘å›¾æ ‡ä»£è¡¨ç½‘ç›˜

      - href: "https://github.com/ceheya"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/216226164"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
        
  footer:
    social:
      - href: "https://viken.top/" # é“¾æ¥
        ariaLabel: è¿”å›æˆ‘çš„ä¸»é¡µ # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: è¿”å›æˆ‘çš„ä¸»é¡µ # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:home-2-line"
      
      - href: "https://pan.viken.top/"
        ariaLabel: "å‰å¾€æˆ‘çš„ç½‘ç›˜"
        title: "å‰å¾€æˆ‘çš„ç½‘ç›˜"
        svg: "ri:cloud-line"  # äº‘å›¾æ ‡ä»£è¡¨ç½‘ç›˜

      - href: "https://github.com/ceheya"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/216226164"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
